export const restArray = [
  {
    id: 0,
    title: 'Пицца плюс',
    time: 50,
    price: 900,
    raiting: 4.5,
    type: 'Пицца',
    img: 'PizzaPlus.jpg',
  },
  {
    id: 1,
    title: 'Пицца Тануки',
    time: 50,
    price: 900,
    raiting: 4.5,
    type: 'Пицца',
    img: 'Tanuki.jpg',
  },
  {
    id: 2,
    title: 'Food Band',
    time: 50,
    price: 900,
    raiting: 4.5,
    type: 'Пицца',
    img: 'FoodBand.jpg',
  },
  {
    id: 3,
    title: 'Жадина-пицца',
    time: 50,
    price: 900,
    raiting: 4.5,
    type: 'Пицца',
    img: 'Zhadina.jpg',
  },
  {
    id: 4,
    title: 'Точка еды',
    time: 50,
    price: 900,
    raiting: 4.5,
    type: 'Пицца',
    img: 'TochkaEdi.jpg',
  },
  {
    id: 5,
    title: 'PizzaBurger',
    time: 50,
    price: 900,
    raiting: 4.5,
    type: 'Пицца',
    img: 'PizzaBurger.jpg',
  },
]